name: Environmental Seal
folder: null
sort: 0
flags:
  cf:
    id: temp_u0ce34u73r
    path: References#/CF_SEP/Qualities#/CF_SEP/Armour Qualities
    color: '#000000'
_id: 6tdrtFwkwKVzV22D
pages:
  - name: Environmental Seal
    type: text
    title:
      show: false
      level: 1
    text:
      format: 1
      content: "<p>+10 pr X to resist particle storms (ash/sand).\_</p>"
    _stats:
      coreVersion: '13.342'
      systemId: null
      systemVersion: null
      createdTime: null
      modifiedTime: null
      lastModifiedBy: null
      compendiumSource: null
      duplicateSource: null
      exportSource: null
    _id: d6vWKYQv0IGgRi0w
    system: {}
    image: {}
    video:
      controls: true
      volume: 0.5
    src: null
    sort: 0
    ownership:
      default: -1
    flags: {}
    category: null
    _key: '!journal.pages!6tdrtFwkwKVzV22D.d6vWKYQv0IGgRi0w'
_stats:
  coreVersion: '13.342'
  systemId: null
  systemVersion: null
  createdTime: null
  modifiedTime: null
  lastModifiedBy: null
  compendiumSource: null
  duplicateSource: null
  exportSource: null
ownership:
  default: 0
  eeXhsDlbzUBZOXZT: 3
categories: []
_key: '!journal!6tdrtFwkwKVzV22D'

